package telas;

import banco.DAO;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Formatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import users.Paciente;
import users.Usuario;

/**
 *
 * @author henri
 */
public class TelaCadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPaciente
     */
    public TelaCadastroPaciente() throws ViaCEPException {
        super("Gerenciamento de Pacientes");
        initComponents();
        setLocationRelativeTo(null);
        try {
            readJTable();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void readJTable() throws Exception {
        DefaultTableModel pacientes = (DefaultTableModel) jTablePacientesCadastrados.getModel();
        DAO dao = new DAO();
        pacientes.setNumRows(0);
        for (Paciente p : dao.mostraPaciente()) {

            pacientes.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getCpf(),
                p.getNasctoo(),
                p.getIdade(),
                p.getTelefone(),
                p.getEmail(),
                p.getCep(),
                p.getRua(),
                p.getNumero(),
                p.getComplemento(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.isAreaSaude(),
                p.getDose(),
                p.getVacinacao(),
                p.getVacinacao2(),
                p.getPrioridade(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNascimento = new javax.swing.JLabel();
        jLabelProfissao = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelDose = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        jFormattedTextFieldNRua = new javax.swing.JFormattedTextField();
        jLabelCEP = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelNumeroCasa = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelBairro1 = new javax.swing.JLabel();
        jLabelComplemento1 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        ButtonLimpar = new javax.swing.JButton();
        ButtonSalvar1 = new javax.swing.JButton();
        ButtonConsultaCep = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxAreaSaude = new javax.swing.JComboBox<>();
        jComboBoxDose = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelNomePesquisa = new javax.swing.JLabel();
        jTextFieldProcurar = new javax.swing.JTextField();
        jButtonPesquisarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientesCadastrados = new javax.swing.JTable();
        ButtonExcluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelFundo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Central de Pacientes");

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Retornarzinho2.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logoutizinho.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 60);

        jPanel2.setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        jPanel2.add(jLabelNome);
        jLabelNome.setBounds(40, 40, 50, 30);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(90, 40, 220, 30);

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCPF.setText("CPF:");
        jPanel2.add(jLabelCPF);
        jLabelCPF.setBounds(410, 120, 40, 30);

        jLabelNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNascimento.setText("Nascimento:");
        jPanel2.add(jLabelNascimento);
        jLabelNascimento.setBounds(370, 40, 150, 30);

        jLabelProfissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProfissao.setText("A. Saúde:");
        jPanel2.add(jLabelProfissao);
        jLabelProfissao.setBounds(10, 120, 80, 30);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(450, 120, 120, 30);

        jLabelCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCelular.setText("Celular:");
        jPanel2.add(jLabelCelular);
        jLabelCelular.setBounds(390, 80, 60, 30);

        jTextFieldRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRuaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldRua);
        jTextFieldRua.setBounds(90, 200, 220, 30);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(40, 80, 50, 30);

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldCelular);
        jFormattedTextFieldCelular.setBounds(450, 80, 120, 30);

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(90, 80, 220, 30);

        try {
            jTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jTextFieldCEP);
        jTextFieldCEP.setBounds(90, 160, 220, 30);

        jLabelDose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDose.setText("Dose:");
        jPanel2.add(jLabelDose);
        jLabelDose.setBounds(30, 280, 60, 30);

        jLabelRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRua.setText("Rua:");
        jPanel2.add(jLabelRua);
        jLabelRua.setBounds(40, 200, 50, 30);

        jFormattedTextFieldNRua.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldNRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNRuaActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldNRua);
        jFormattedTextFieldNRua.setBounds(450, 240, 120, 30);

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCEP.setText("CEP:");
        jPanel2.add(jLabelCEP);
        jLabelCEP.setBounds(40, 160, 50, 30);

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado:");
        jPanel2.add(jLabelEstado);
        jLabelEstado.setBounds(390, 160, 60, 30);

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCidade.setText("Cidade:");
        jPanel2.add(jLabelCidade);
        jLabelCidade.setBounds(390, 200, 60, 30);

        jTextFieldCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldCidade);
        jTextFieldCidade.setBounds(450, 200, 120, 30);

        jLabelNumeroCasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroCasa.setText("Nº:");
        jPanel2.add(jLabelNumeroCasa);
        jLabelNumeroCasa.setBounds(410, 240, 40, 30);

        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEstado);
        jTextFieldEstado.setBounds(450, 160, 120, 30);

        jLabelBairro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBairro1.setText("Bairro:");
        jPanel2.add(jLabelBairro1);
        jLabelBairro1.setBounds(30, 240, 60, 30);

        jLabelComplemento1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelComplemento1.setText("Complemento:");
        jPanel2.add(jLabelComplemento1);
        jLabelComplemento1.setBounds(350, 280, 100, 30);

        jTextFieldBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(90, 240, 220, 30);

        jTextFieldComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldComplemento);
        jTextFieldComplemento.setBounds(450, 280, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("*");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 80, 31, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("*");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 120, 31, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("*");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(580, 40, 31, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("*");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(580, 120, 31, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("*");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 10, 31, 20);

        try {
            jFormattedTextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldDataNascimento);
        jFormattedTextFieldDataNascimento.setBounds(450, 40, 120, 30);

        ButtonLimpar.setText("Limpar");
        ButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonLimpar);
        ButtonLimpar.setBounds(100, 360, 110, 25);

        ButtonSalvar1.setText("Salvar");
        ButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvar1ActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSalvar1);
        ButtonSalvar1.setBounds(380, 360, 120, 25);

        ButtonConsultaCep.setText("Consultar CEP");
        ButtonConsultaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultaCepActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonConsultaCep);
        ButtonConsultaCep.setBounds(240, 360, 110, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("*");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(320, 40, 31, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Campos Obrigatórios!");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 0, 130, 40);

        jComboBoxAreaSaude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jComboBoxAreaSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAreaSaudeActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxAreaSaude);
        jComboBoxAreaSaude.setBounds(90, 121, 220, 30);

        jComboBoxDose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Dose", "2º Dose" }));
        jPanel2.add(jComboBoxDose);
        jComboBoxDose.setBounds(90, 280, 220, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("VaciLife, transformando vidas para um novo começo!");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(140, 400, 340, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, -20, 610, 490);

        jTabbedPane1.addTab("Cadastrar Paciente", jPanel2);

        jPanel3.setLayout(null);

        jLabelNomePesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomePesquisa.setText("Nome:");
        jPanel3.add(jLabelNomePesquisa);
        jLabelNomePesquisa.setBounds(20, 20, 60, 30);

        jTextFieldProcurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jTextFieldProcurar);
        jTextFieldProcurar.setBounds(70, 20, 180, 30);

        jButtonPesquisarNome.setText("Pesquisar");
        jButtonPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarNomeActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPesquisarNome);
        jButtonPesquisarNome.setBounds(260, 20, 90, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jTablePacientesCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Nascimento", "Idade", "Telefone", "Email", "CEP", "Rua", "Nº Casa", "Complemento", "Bairro", "Cidade", "Estado", "A. Saúde", "Dose", "Data 1º Dose", "Data 2º Dose", "Prioridade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePacientesCadastrados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTablePacientesCadastrados);
        if (jTablePacientesCadastrados.getColumnModel().getColumnCount() > 0) {
            jTablePacientesCadastrados.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(14).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(15).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(16).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(17).setPreferredWidth(100);
            jTablePacientesCadastrados.getColumnModel().getColumn(18).setPreferredWidth(100);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 580, 330);

        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonExcluir);
        ButtonExcluir.setBounds(490, 20, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("VaciLife, Transformando Vidas Para um Novo Recomeço!");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(120, 400, 340, 40);

        jLabelFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        jPanel3.add(jLabelFundo2);
        jLabelFundo2.setBounds(0, -20, 610, 470);

        jTabbedPane1.addTab("Consultar Paciente", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 610, 470);

        setSize(new java.awt.Dimension(620, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipalAdmin tela2 = new TelaPrincipalAdmin();
        tela2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRuaActionPerformed

    private void ButtonConsultaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultaCepActionPerformed
        ViaCEP cep = new ViaCEP();
        String cepp = jTextFieldCEP.getText();
        cepp = cepp.replace(" ", "");
        cepp = cepp.replace("-", "");
        try {
            cep.buscar(cepp);
        } catch (ViaCEPException ex) {
            Logger.getLogger(TelaCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTextFieldRua.setText(cep.getLogradouro());
        jTextFieldBairro.setText(cep.getBairro());
        jTextFieldCidade.setText(cep.getLocalidade());
        jTextFieldEstado.setText(cep.getUf());


    }//GEN-LAST:event_ButtonConsultaCepActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void ButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvar1ActionPerformed
        if (jFormattedTextFieldDataNascimento.getText().equals("  /  /    ") || jFormattedTextFieldDataNascimento == null) {
            JOptionPane.showMessageDialog(null, "Favor inserir a Data de Nascimento do paciente!");
        } else {
            String nome = jTextFieldNome.getText();
            String cpf = jFormattedTextFieldCPF.getText();
            int dia = Integer.parseInt(jFormattedTextFieldDataNascimento.getText().substring(0, 2));
            int mes = Integer.parseInt(jFormattedTextFieldDataNascimento.getText().substring(3, 5));
            int ano = Integer.parseInt(jFormattedTextFieldDataNascimento.getText().substring(6));

            Calendar dataNasc = Calendar.getInstance();
            dataNasc.set(Calendar.YEAR, ano);
            dataNasc.set(Calendar.MONTH, mes - 1);
            dataNasc.set(Calendar.DAY_OF_MONTH, dia);

            Date nascimento = dataNasc.getTime();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            String dataNascimento = sdf.format(nascimento);

            Calendar hoje = Calendar.getInstance();
            //Date hoje = c.getTime();

            //String dataHoje = sdf.format(hoje);
            int age = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);
            dataNasc.add(Calendar.YEAR, age);

            if (hoje.before(dataNasc)) {
                age--;
            }

            String email = jTextFieldEmail.getText();
            String cep = jTextFieldCEP.getText();
            String rua = jTextFieldRua.getText();
            int numero = Integer.parseInt(jFormattedTextFieldNRua.getText());
            String complemento = jTextFieldComplemento.getText();
            String bairro = jTextFieldBairro.getText();
            String cidade = jTextFieldCidade.getText();
            String estado = jTextFieldEstado.getText();
            Object profissao = jComboBoxAreaSaude.getSelectedItem();
            profissao = profissao.toString();
            int prioridade;

            String telefone = jFormattedTextFieldCelular.getText();
            Object escolhaDose = jComboBoxDose.getSelectedItem();
            escolhaDose = escolhaDose.toString();
            int dose = 1;

            int idade = age;
            boolean areaSaude = false;

            if (jTextFieldNome.getText().equals("") || jTextFieldNome == null || jTextFieldEmail.getText().equals("") || jTextFieldEmail == null
                    || dataNascimento.equals("") || dataNascimento == null || jFormattedTextFieldCPF.getText().equals("   .   .   -  ") || jFormattedTextFieldCPF == null) {
                JOptionPane.showMessageDialog(null, "Favor cadastrar todos os campos obrigatórios(*)!");
            } else {
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro de novo paciente?");
                if (escolha == JOptionPane.YES_OPTION) {
                    try {
                        if (profissao.equals("Sim")) {
                            areaSaude = true;
                        } else if (profissao.equals("Não")) {
                            areaSaude = false;
                        }

                        if (escolhaDose.equals("1º Dose")) {
                            dose = 1;
                        } else if (escolhaDose.equals("2º Dose")) {
                            dose = 2;
                        }

                        if (idade >= 70) {
                            prioridade = 1;
                        } else if (areaSaude) {
                            prioridade = 2;
                        } else {
                            prioridade = 3;
                        }

                        Paciente paciente = new Paciente(nome, cpf, dataNascimento, email, cep, rua, numero, complemento, bairro, cidade, estado, idade, areaSaude, telefone, dose, prioridade);//true pq é um administrador
                        DAO dao = new DAO();
                        dao.inserirPaciente(paciente);
                        JOptionPane.showMessageDialog(null, "Paciente cadastrado com sucesso!");
                        limpaCampos();
                        readJTable();
                    } catch (Exception e) {
                        Logger.getLogger(TelaCadastroPaciente.class.getName()).log(Level.SEVERE, null, e);
                        JOptionPane.showMessageDialog(null, "Erro ao cadastrar. Verifique se todos os campos estão preenchidos corretamente ou se seu email e cpf já não está cadastrado!\n"
                                + "Caso esteja tudo certo e o problema persistir, contate um de nossos suportes!", "Falha no Cadastro", JOptionPane.WARNING_MESSAGE);
                        e.printStackTrace();
                    }

                }
            }
        }
    }//GEN-LAST:event_ButtonSalvar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCEP.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldCelular.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldNRua.setText("");
        jTextFieldBairro.setText("");
        jTextFieldComplemento.setText("");
    }//GEN-LAST:event_ButtonLimparActionPerformed

    private void jFormattedTextFieldNRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNRuaActionPerformed

    private void jComboBoxAreaSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAreaSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAreaSaudeActionPerformed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        int pegarSelecao = jTablePacientesCadastrados.getSelectedRow();
        int escolha = JOptionPane.showConfirmDialog(null, "Remover Paciente?");
        if (escolha == JOptionPane.YES_OPTION) {

            try {
                Object iddd = jTablePacientesCadastrados.getValueAt(pegarSelecao, 0);
                String idd = iddd.toString();
                int id = Integer.parseInt(idd);
                Paciente p = new Paciente(id);
                DAO dao = new DAO();
                dao.removerPaciente(p);
                JOptionPane.showMessageDialog(null, "Paciente removido com sucesso!");
                readJTable();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void jButtonPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarNomeActionPerformed

        String nome = "%" + jTextFieldProcurar.getText() + "%";

        DAO dao = new DAO();
        ArrayList<Paciente> pct = new ArrayList<Paciente>();
        try {
            pct = dao.buscarPacienteCadastrado(nome);
        } catch (Exception ex) {
            Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel paciente = (DefaultTableModel) jTablePacientesCadastrados.getModel();
        paciente.setNumRows(0);

        for (Paciente p : pct) {
            paciente.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getCpf(),
                p.getNasctoo(),
                p.getIdade(),
                p.getTelefone(),
                p.getEmail(),
                p.getCep(),
                p.getRua(),
                p.getNumero(),
                p.getComplemento(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.isAreaSaude(),
                p.getDose(),
                p.getVacinacao(),
                p.getVacinacao2(),
                p.getPrioridade()
            });
        }
    }//GEN-LAST:event_jButtonPesquisarNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public void limpaCampos() {
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCEP.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldCelular.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldNRua.setText("");
        jTextFieldBairro.setText("");
        jTextFieldComplemento.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadastroPaciente().setVisible(true);
                } catch (ViaCEPException ex) {
                    Logger.getLogger(TelaCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConsultaCep;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JButton ButtonLimpar;
    private javax.swing.JButton ButtonSalvar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPesquisarNome;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxAreaSaude;
    private javax.swing.JComboBox<String> jComboBoxDose;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldNRua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBairro1;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento1;
    private javax.swing.JLabel jLabelDose;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundo2;
    private javax.swing.JLabel jLabelNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomePesquisa;
    private javax.swing.JLabel jLabelNumeroCasa;
    private javax.swing.JLabel jLabelProfissao;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePacientesCadastrados;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JFormattedTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldProcurar;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables

}
