package telas;

import java.util.Calendar;
import javax.swing.JOptionPane;
import Relatorio.ExtracaoRelatorios;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author henri
 */
public class TelaExtrairRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form TelaExtrairRelatorio
     */
    public TelaExtrairRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonExtrairRelatorio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxIdades = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMediaVac = new javax.swing.JTextField();
        jFormattedTextFieldAte = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDe = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDoses = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2Dose = new javax.swing.JTextField();
        jTextField1Dose = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Retornarzinho2.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Extração de Relatórios");

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logoutizinho.png"))); // NOI18N
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButtonSair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButtonLogout)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 70);

        jButtonExtrairRelatorio.setText("Extrair Relatório");
        jButtonExtrairRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtrairRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExtrairRelatorio);
        jButtonExtrairRelatorio.setBounds(80, 280, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatório (1).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 270, 290, 200);

        jComboBoxIdades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menor de 50 Anos", "50 - 69 Anos", "70 - 89 Anos", "Maior de 90 Anos" }));
        jComboBoxIdades.setBorder(null);
        getContentPane().add(jComboBoxIdades);
        jComboBoxIdades.setBounds(80, 230, 150, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Até:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 50, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Média diária de Doses");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 280, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Idade:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 230, 50, 40);

        jTextFieldMediaVac.setEditable(false);
        getContentPane().add(jTextFieldMediaVac);
        jTextFieldMediaVac.setBounds(440, 280, 120, 40);

        try {
            jFormattedTextFieldAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldAte);
        jFormattedTextFieldAte.setBounds(80, 180, 150, 40);

        try {
            jFormattedTextFieldDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDeActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldDe);
        jFormattedTextFieldDe.setBounds(80, 130, 150, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("De:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 130, 60, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("VaciLife, transformando vidas para um novo começo!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 380, 350, 40);

        jTextFieldDoses.setEditable(false);
        getContentPane().add(jTextFieldDoses);
        jTextFieldDoses.setBounds(440, 130, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("1ª Dose");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 180, 120, 40);

        jTextField2Dose.setEditable(false);
        getContentPane().add(jTextField2Dose);
        jTextField2Dose.setBounds(440, 230, 120, 40);

        jTextField1Dose.setEditable(false);
        getContentPane().add(jTextField1Dose);
        jTextField1Dose.setBounds(440, 180, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("2ª Dose");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 230, 120, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Doses Distribuidas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 130, 120, 40);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 610, 440);

        setSize(new java.awt.Dimension(624, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TelaPrincipalAdmin tp = new TelaPrincipalAdmin();
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonExtrairRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtrairRelatorioActionPerformed
        String dia = jFormattedTextFieldDe.getText().substring(0, 2);
        String mes = jFormattedTextFieldDe.getText().substring(3, 5);
        String ano = jFormattedTextFieldDe.getText().substring(6);

        String dataInicial;
        dataInicial = ano + "-" + mes + "-" + dia;

        String diaFinal = jFormattedTextFieldAte.getText().substring(0, 2);
        String mesFinal = jFormattedTextFieldAte.getText().substring(3, 5);
        String anoFinal = jFormattedTextFieldAte.getText().substring(6);
        
        Calendar inicial = Calendar.getInstance();
        inicial.set(Calendar.YEAR, Integer.parseInt(ano));
        inicial.set(Calendar.MONTH, Integer.parseInt(mes)-1);
        inicial.set(Calendar.DAY_OF_MONTH, Integer.parseInt(dia));
        
        Calendar dataFinall = Calendar.getInstance();
        dataFinall.set(Calendar.YEAR, Integer.parseInt(anoFinal));
        dataFinall.set(Calendar.MONTH, Integer.parseInt(mesFinal)-1);
        dataFinall.set(Calendar.DAY_OF_MONTH, Integer.parseInt(diaFinal));
        
        
        Date data1 = new Date(), data2 = new Date();
	
		data1.setTime(inicial.getTimeInMillis());
		
		//Pega a segunda data
		
		data2.setTime(dataFinall.getTimeInMillis());

		
		float dias = (data2.getTime() - data1.getTime())/1000/60/60/24;
                
                
        

        String dataFinal;
        dataFinal = anoFinal + "-" + mesFinal + "-" + diaFinal;
        DecimalFormat formatter = new DecimalFormat("0.00");

        Object FaixaEtaria = jComboBoxIdades.getSelectedItem();
        FaixaEtaria = FaixaEtaria.toString();

        if (jFormattedTextFieldDe.getText().equals("  /  /    ") || jFormattedTextFieldAte.getText().equals("  /  /   ")) {
            JOptionPane.showMessageDialog(null, "Insira uma data válida para que a consulta possa ser feita.", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            if (FaixaEtaria.equals("Menor de 50 Anos")) {
                try {
                    int nVacinados = ExtracaoRelatorios.contaVacinadosMenor50(dataInicial, dataFinal);
                    String vacinados = NumberFormat.getInstance().format(nVacinados);
                    jTextFieldDoses.setText(vacinados + " DOSES");
                     float mediavac = nVacinados / dias;
                     
                     jTextFieldMediaVac.setText(formatter.format(mediavac)+ " vacinados");
                    //JOptionPane.showMessageDialog(null, "Nº de Pacientes vacinados com faixa etária " + FaixaEtaria.toString() + " para o período selecionado é: \n" + nVacinados + " Pacientes.", "Extração de Relatórios", JOptionPane.INFORMATION_MESSAGE);
                    
                    int nVacinados1Dose = ExtracaoRelatorios.contaVacinados1Dose50Anos(dataInicial, dataFinal);
                    String vacinados1 = NumberFormat.getInstance().format(nVacinados1Dose);
                    jTextField1Dose.setText(vacinados1 + " Pacientes");
                    
                    
                    int nVacinados2Dose = ExtracaoRelatorios.contaVacinados2Dose50Anos(dataInicial, dataFinal);
                    String vacinados2 = NumberFormat.getInstance().format(nVacinados2Dose);
                    jTextField2Dose.setText(vacinados2 + " Pacientes");
                } catch (Exception ex) {
                    Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (FaixaEtaria.equals("50 - 69 Anos")) {
                try {
                    int nVacinados = ExtracaoRelatorios.contaVacinados50Anos69(dataInicial, dataFinal);
                    String vacinados = NumberFormat.getInstance().format(nVacinados);
                    jTextFieldDoses.setText(vacinados + " DOSES");
                    float mediavac = nVacinados / dias;
                    jTextFieldMediaVac.setText(formatter.format(mediavac)+ " vacinados");;
                    //JOptionPane.showMessageDialog(null, "Nº de Pacientes vacinados com faixa etária " + FaixaEtaria.toString() + " para o período selecionado é: \n" + nVacinados + " Pacientes.");
                
                    int nVacinados1Dose = ExtracaoRelatorios.contaVacinados1Dose50Anos69(dataInicial, dataFinal);
                    String vacinados1 = NumberFormat.getInstance().format(nVacinados1Dose);
                    jTextField1Dose.setText(vacinados1 + " Pacientes");
                
                    int nVacinados2Dose = ExtracaoRelatorios.contaVacinados2Dose50Anos69(dataInicial, dataFinal);
                    String vacinados2 = NumberFormat.getInstance().format(nVacinados2Dose);
                    jTextField2Dose.setText(vacinados2 + " Pacientes");
                } catch (Exception ex) {
                    Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (FaixaEtaria.equals("70 - 89 Anos")) {
                try {
                    int nVacinados = ExtracaoRelatorios.contaVacinados70Anos89(dataInicial, dataFinal);
                    String vacinados = NumberFormat.getInstance().format(nVacinados);
                    jTextFieldDoses.setText(vacinados + " DOSES");
                    float mediavac = nVacinados / dias;
                    jTextFieldMediaVac.setText(formatter.format(mediavac)+ " vacinados");
                    //JOptionPane.showMessageDialog(null, "Nº de Pacientes vacinados com faixa etária " + FaixaEtaria.toString() + " para o período selecionado é: \n" + nVacinados + " Pacientes.");
                
                    int nVacinados1Dose = ExtracaoRelatorios.contaVacinados1Dose70Anos89(dataInicial, dataFinal);
                    String vacinados1 = NumberFormat.getInstance().format(nVacinados1Dose);
                    jTextField1Dose.setText(vacinados1 + " Pacientes");
                
                    int nVacinados2Dose = ExtracaoRelatorios.contaVacinados2Dose70Anos89(dataInicial, dataFinal);
                    String vacinados2 = NumberFormat.getInstance().format(nVacinados2Dose);
                    jTextField2Dose.setText(vacinados2 + " Pacientes");
                } catch (Exception ex) {
                    Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (FaixaEtaria.equals("Maior de 90 Anos")) {
                try {
                    int nVacinados = ExtracaoRelatorios.contaVacinados90Anos(dataInicial, dataFinal);
                    String vacinados = NumberFormat.getInstance().format(nVacinados);
                    jTextFieldDoses.setText(vacinados + " DOSES");
                    float mediavac = nVacinados / dias;
                    jTextFieldMediaVac.setText(formatter.format(mediavac)+ " vacinados");
                    //JOptionPane.showMessageDialog(null, "Nº de Pacientes vacinados com faixa etária " + FaixaEtaria.toString() + " para o período selecionado é: \n" + nVacinados + " Pacientes.");
                
                    int nVacinados1Dose = ExtracaoRelatorios.contaVacinados1Dose90Anos(dataInicial, dataFinal);
                    String vacinados1 = NumberFormat.getInstance().format(nVacinados1Dose);
                    jTextField1Dose.setText(vacinados1 + " Pacientes");
                
                    int nVacinados2Dose = ExtracaoRelatorios.contaVacinados2Dose90Anos(dataInicial, dataFinal);
                    String vacinados2 = NumberFormat.getInstance().format(nVacinados2Dose);
                    jTextField2Dose.setText(vacinados2 + " Pacientes");
                } catch (Exception ex) {
                    Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonExtrairRelatorioActionPerformed

    private void jFormattedTextFieldDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDeActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExtrairRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExtrairRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExtrairRelatorio;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxIdades;
    private javax.swing.JFormattedTextField jFormattedTextFieldAte;
    private javax.swing.JFormattedTextField jFormattedTextFieldDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1Dose;
    private javax.swing.JTextField jTextField2Dose;
    private javax.swing.JTextField jTextFieldDoses;
    private javax.swing.JTextField jTextFieldMediaVac;
    // End of variables declaration//GEN-END:variables
}
