/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.DAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import users.Paciente;
import users.Usuario;

/**
 *
 * @author henri
 */
public class TelaVacinacao1Dose extends javax.swing.JFrame {

    /**
     * Creates new form TelaVacinacao1Dose
     */
    public TelaVacinacao1Dose() {
        super("Gerenciamento da Primeira dose");
        initComponents();
        setLocationRelativeTo(null);
        try {
            readJTable();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void readJTable() throws Exception {
        DefaultTableModel pacientes = (DefaultTableModel) jTablePacientes.getModel();
        DAO dao = new DAO();
        pacientes.setNumRows(0);
        for (Paciente p : dao.mostraPacienteDose1()) {

            pacientes.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getCpf(),
                p.getNasctoo(),
                p.getIdade(),
                p.isAreaSaude(),
                p.isVacinado()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonConfirmaVacinacao = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jComboBoxEscolhaPesquisa = new javax.swing.JComboBox<>();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Design_sem_nome__1_-removebg-preview.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(210, 0, 210, 120);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome do Paciente", "CPF", "Data de Nascimento", "Idade", "A.Saúde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);
        if (jTablePacientes.getColumnModel().getColumnCount() > 0) {
            jTablePacientes.getColumnModel().getColumn(0).setResizable(false);
            jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTablePacientes.getColumnModel().getColumn(4).setResizable(false);
            jTablePacientes.getColumnModel().getColumn(4).setPreferredWidth(15);
            jTablePacientes.getColumnModel().getColumn(5).setResizable(false);
            jTablePacientes.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 610, 190);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(530, 110, 90, 30);

        jButtonConfirmaVacinacao.setText("Confirmar Vacinação");
        jButtonConfirmaVacinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaVacinacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmaVacinacao);
        jButtonConfirmaVacinacao.setBounds(10, 109, 190, 30);
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(350, 110, 170, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit3.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(600, 10, 20, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FILA DE VACINAÇÃO - 1ª DOSE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 210, 20);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaRetorna.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(10, 80, 20, 20);

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logoutizinho.png"))); // NOI18N
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout);
        jButtonLogout.setBounds(10, 10, 40, 30);

        jComboBoxEscolhaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "Idade" }));
        getContentPane().add(jComboBoxEscolhaPesquisa);
        jComboBoxEscolhaPesquisa.setBounds(223, 110, 120, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 660, 360);

        setSize(new java.awt.Dimension(640, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipalAtendente telaVolta = new TelaPrincipalAtendente();
        telaVolta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonConfirmaVacinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaVacinacaoActionPerformed

        int escolha = JOptionPane.showConfirmDialog(null, "Confirmar vacinação?");
        if (escolha == JOptionPane.YES_OPTION) {
            for (int i = 0; i < jTablePacientes.getRowCount(); i++) {
                if (jTablePacientes.getValueAt(i, 0).toString().equals("")) {
                    JOptionPane.showMessageDialog(null, "Erro...", "Não existe dependentes com esse cnpj", JOptionPane.ERROR_MESSAGE);
                }
            } 

            try {

                int pegaSelecao = jTablePacientes.getSelectedRow();
                String idd = jTablePacientes.getValueAt(pegaSelecao, 0).toString();
                int id = Integer.parseInt(idd);

                int dose = 2;
                Calendar today = Calendar.getInstance();
                Date hoje = today.getTime();

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dataVacinacao = sdf.format(hoje);

                Paciente p = new Paciente(id, dataVacinacao, dose);
                DAO dao = new DAO();
                dao.vacinaPacienteDose1(p);
                readJTable();
                JOptionPane.showMessageDialog(null, "Vacinação confirmada! Favor informar a data da Segunda dose ao paciente!");
            } catch (Exception ex) {
                Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Não foi possível encontrar o paciente selecionado para vacinação, caso você tenha selecionado, entre em contato com o suporte!", "ERRO", 
                        JOptionPane.ERROR_MESSAGE);
            }       
        }
    }//GEN-LAST:event_jButtonConfirmaVacinacaoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        Object escolhaPesquisa = jComboBoxEscolhaPesquisa.getSelectedItem();

        if (escolhaPesquisa.toString().equals("Nome")) {
            String nome = "%" + jTextFieldPesquisar.getText() + "%";

            DAO dao = new DAO();
            ArrayList<Paciente> pct = new ArrayList<Paciente>();
            try {
                pct = dao.buscarPacienteNome(nome);
            } catch (Exception ex) {
                Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(Level.SEVERE, null, ex);
            }

            DefaultTableModel paciente = (DefaultTableModel) jTablePacientes.getModel();
            paciente.setNumRows(0);

            for (Paciente p : pct) {
                paciente.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNome(),
                    p.getCpf(),
                    p.getNasctoo(),
                    p.getIdade(),
                    p.isAreaSaude()
                });

            }
        } else if (escolhaPesquisa.toString().equals("CPF")) {
            String cpf = "%" + jTextFieldPesquisar.getText() + "%";

            DAO dao = new DAO();
            ArrayList<Paciente> pct = new ArrayList<Paciente>();
            try {
                pct = dao.buscarPacienteCPF(cpf);
            } catch (Exception ex) {
                Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(Level.SEVERE, null, ex);
            }

            DefaultTableModel paciente = (DefaultTableModel) jTablePacientes.getModel();
            paciente.setNumRows(0);

            for (Paciente p : pct) {
                paciente.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNome(),
                    p.getCpf(),
                    p.getNasctoo(),
                    p.getIdade(),
                    p.isAreaSaude()
                });

            }
        } else if (escolhaPesquisa.toString().equals("Idade")) {
            String idade = jTextFieldPesquisar.getText();

            DAO dao = new DAO();
            ArrayList<Paciente> pct = new ArrayList<Paciente>();
            try {
                pct = dao.buscarPacienteIdade(Integer.parseInt(idade));
            } catch (Exception ex) {
                Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(Level.SEVERE, null, ex);
            }

            DefaultTableModel paciente = (DefaultTableModel) jTablePacientes.getModel();
            paciente.setNumRows(0);

            for (Paciente p : pct) {
                paciente.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNome(),
                    p.getCpf(),
                    p.getNasctoo(),
                    p.getIdade(),
                    p.isAreaSaude()
                });

            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVacinacao1Dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVacinacao1Dose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton jButtonConfirmaVacinacao;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxEscolhaPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
