/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import users.*;
import banco.*;

/**
 *
 * @author eu
 */
public class TelaPrincipalAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAtendente
     */
    public TelaPrincipalAtendente() {
        initComponents();
        jLabelMensagemOla.setText("Boas vindas novamente!");
    }
    
    public TelaPrincipalAtendente(String nomin) {
        initComponents();
        jLabelMensagemOla.setText("Olá, " + nomin + "!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelVaciLifeLogo = new javax.swing.JLabel();
        jLabelAtendente = new javax.swing.JLabel();
        jButton2Dose = new javax.swing.JButton();
        jButton1Dose = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelMensagemOla = new javax.swing.JLabel();
        jLabel2Dose = new javax.swing.JLabel();
        jLabel1Dose1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabelImgDeFundo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelVaciLifeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Design_sem_nome__1_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabelVaciLifeLogo);
        jLabelVaciLifeLogo.setBounds(100, 0, 230, 120);

        jLabelAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/-_Atendente-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabelAtendente);
        jLabelAtendente.setBounds(290, 20, 190, 60);

        jButton2Dose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Vacininha2.png"))); // NOI18N
        jButton2Dose.setToolTipText("2ª Dose");
        jButton2Dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2DoseActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Dose);
        jButton2Dose.setBounds(300, 140, 110, 90);

        jButton1Dose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Vacininha.png"))); // NOI18N
        jButton1Dose.setToolTipText("1ª Dose");
        jButton1Dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DoseActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Dose);
        jButton1Dose.setBounds(160, 140, 110, 90);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit3.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(550, 20, 20, 20);

        jLabelMensagemOla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMensagemOla.setForeground(new java.awt.Color(0, 102, 102));
        jLabelMensagemOla.setText("Olá,");
        getContentPane().add(jLabelMensagemOla);
        jLabelMensagemOla.setBounds(30, 90, 280, 30);

        jLabel2Dose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2Dose.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2Dose.setText("2ª Dose");
        getContentPane().add(jLabel2Dose);
        jLabel2Dose.setBounds(420, 140, 60, 90);

        jLabel1Dose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1Dose1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1Dose1.setText("1ª Dose");
        getContentPane().add(jLabel1Dose1);
        jLabel1Dose1.setBounds(90, 140, 70, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("VaciLife, transformando vidas para um novo começo!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 280, 380, 20);

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logoutizinho.png"))); // NOI18N
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout);
        jButtonLogout.setBounds(20, 20, 30, 30);

        jLabelImgDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        getContentPane().add(jLabelImgDeFundo);
        jLabelImgDeFundo.setBounds(0, -10, 600, 350);

        setSize(new java.awt.Dimension(600, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButton1DoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DoseActionPerformed
        TelaVacinacao1Dose tela1 = new TelaVacinacao1Dose();
        tela1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1DoseActionPerformed

    private void jButton2DoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2DoseActionPerformed
        TelaVacinacao2Dose tela2 = new TelaVacinacao2Dose();
        tela2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2DoseActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaPrincipalAtendente().setVisible(true);
            }
            
            
        });
        
    }
//    public void setNomeUsuario(){
//        DAO dao = new DAO();
//        
//        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Dose;
    private javax.swing.JButton jButton2Dose;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Dose1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Dose;
    private javax.swing.JLabel jLabelAtendente;
    private javax.swing.JLabel jLabelImgDeFundo;
    private javax.swing.JLabel jLabelMensagemOla;
    private javax.swing.JLabel jLabelVaciLifeLogo;
    // End of variables declaration//GEN-END:variables
}
