/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.DAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import users.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henri
 */
public class TelaCadastroAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPaciente
     */
    public TelaCadastroAtendente() throws Exception {
        super("Gerenciamento de atendentes");
        initComponents();
        setLocationRelativeTo(null);
        readJTableAtd();
    }

    public void readJTableAtd() throws Exception {
        DefaultTableModel atendentes = (DefaultTableModel) jTableAtendentes.getModel();
        DAO dao = new DAO();
        atendentes.setNumRows(0);
        for (Usuario u : dao.mostraUsuarioAtd()) {

            atendentes.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getEmail(),});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ButtonLimpar = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProcurar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtendentes = new javax.swing.JTable();
        ButtonEditar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        jButtonTrocarSenha = new javax.swing.JButton();
        jLabelFundo2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEditarEmail = new javax.swing.JTextField();
        jTextFieldEditarNome1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonOkzinho = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelFundo3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordFieldEditarConfirmarSenha = new javax.swing.JPasswordField();
        jPasswordFieldEditarSenha = new javax.swing.JPasswordField();
        jButtonConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabelFundo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Central de Atendentes");

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Retornarzinho2.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logoutizinho.png"))); // NOI18N
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonVoltar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 60);

        jPanel2.setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        jPanel2.add(jLabelNome);
        jLabelNome.setBounds(10, 70, 50, 30);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 70, 220, 30);

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(60, 120, 220, 30);

        jPasswordFieldSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(430, 70, 150, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        jPanel2.add(jLabelSenha);
        jLabelSenha.setBounds(380, 70, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("*");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 20, 31, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("*");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(290, 70, 31, 30);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(10, 120, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("*");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(290, 120, 31, 30);

        ButtonLimpar.setText("Limpar");
        ButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonLimpar);
        ButtonLimpar.setBounds(40, 220, 90, 25);

        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSalvar);
        ButtonSalvar.setBounds(180, 220, 90, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("*");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(580, 70, 20, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Campos Obrigatórios!");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 30, 150, 20);

        jLabelConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConfirmarSenha.setText("Confirmar Senha:");
        jPanel2.add(jLabelConfirmarSenha);
        jLabelConfirmarSenha.setBounds(310, 120, 120, 30);

        jPasswordFieldConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jPasswordFieldConfirmarSenha);
        jPasswordFieldConfirmarSenha.setBounds(430, 120, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("*");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(580, 120, 31, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 630, 270);

        jTabbedPane1.addTab("Cadastrar Atendente", jPanel2);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 60, 30);

        jTextFieldProcurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jTextFieldProcurar);
        jTextFieldProcurar.setBounds(70, 20, 180, 30);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(260, 20, 90, 30);

        jTableAtendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAtendentes);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 580, 140);

        ButtonEditar.setText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonEditar);
        ButtonEditar.setBounds(40, 220, 90, 25);

        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonExcluir);
        ButtonExcluir.setBounds(180, 220, 90, 25);

        jButtonTrocarSenha.setText("Trocar Senha");
        jButtonTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrocarSenhaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonTrocarSenha);
        jButtonTrocarSenha.setBounds(480, 220, 110, 25);

        jLabelFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        jPanel3.add(jLabelFundo2);
        jLabelFundo2.setBounds(0, -10, 626, 270);

        jTabbedPane1.addTab("Consultar Atendente", jPanel3);

        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Email:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(150, 120, 50, 30);
        jPanel4.add(jTextFieldEditarEmail);
        jTextFieldEditarEmail.setBounds(200, 120, 220, 30);
        jPanel4.add(jTextFieldEditarNome1);
        jTextFieldEditarNome1.setBounds(200, 70, 220, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nome:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(150, 70, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("*");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(430, 120, 31, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("*");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 170, 31, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("*");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(430, 70, 31, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Campos Obrigatórios!");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(30, 170, 150, 20);

        jButtonOkzinho.setText("OK");
        jButtonOkzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkzinhoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonOkzinho);
        jButtonOkzinho.setBounds(200, 160, 220, 25);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonLimpar);
        jButtonLimpar.setBounds(40, 220, 90, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Editar Informações de Atendente");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(190, 20, 250, 30);

        jLabelFundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        jPanel4.add(jLabelFundo3);
        jLabelFundo3.setBounds(0, -7, 614, 270);

        jTabbedPane1.addTab("Editar Atendente", jPanel4);

        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Confirmar Senha:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(110, 120, 110, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Nova Senha:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(140, 80, 80, 30);
        jPanel5.add(jPasswordFieldEditarConfirmarSenha);
        jPasswordFieldEditarConfirmarSenha.setBounds(230, 120, 180, 30);
        jPanel5.add(jPasswordFieldEditarSenha);
        jPasswordFieldEditarSenha.setBounds(230, 80, 180, 30);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonConfirmar);
        jButtonConfirmar.setBounds(230, 160, 180, 30);

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(40, 220, 90, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Atualização de Senha Atendente");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(200, 30, 240, 30);

        jLabelFundo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/design-de-modelo-de-papel-de-parede-medico-abstrato_53876-61805.jpg"))); // NOI18N
        jPanel5.add(jLabelFundo4);
        jLabelFundo4.setBounds(-20, -10, 630, 280);

        jTabbedPane1.addTab("Atualizar Senha", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 610, 290);

        setSize(new java.awt.Dimension(617, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipalAdmin tela2 = new TelaPrincipalAdmin();
        tela2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void ButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmarSenha.setText("");
    }//GEN-LAST:event_ButtonLimparActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        String nomeAtd = jTextFieldNome.getText();
        String emailAtd = jTextFieldEmail.getText();
        String senha = new String(jPasswordFieldSenha.getPassword());
        String confirmaSenha = new String(jPasswordFieldConfirmarSenha.getPassword());
        if (nomeAtd == null || nomeAtd.length() == 0
                || emailAtd == null || emailAtd.length() == 0 || senha == null || senha.length() == 0
                || confirmaSenha == null || confirmaSenha.length() == 0) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
        } else if (senha.equals(confirmaSenha)) {
            try {
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro de novo atendente?");
                if (escolha == JOptionPane.YES_OPTION) {
                    Usuario user = new Usuario(nomeAtd, emailAtd, senha, true);//true pq é um atendente;
                    DAO dao = new DAO();
                    dao.inserirAtendente(user);
                    JOptionPane.showMessageDialog(null, "Usuario atendente cadastrado com sucesso");
                    jTextFieldNome.setText("");
                    jTextFieldEmail.setText("");
                    jPasswordFieldSenha.setText("");
                    jPasswordFieldConfirmarSenha.setText("");
                    readJTableAtd();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha técnica, verifique se seu email já não está cadastrado. Caso não esteja, consulte o suporte!", "Falha no Cadastro", JOptionPane.WARNING_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Os campos de senha devem ser os mesmos!");
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        int pegarSelecao = jTableAtendentes.getSelectedRow();
        int escolha = JOptionPane.showConfirmDialog(null, "Remover atendente?");
        if (escolha == JOptionPane.YES_OPTION) {
            try {
                Object iddd = jTableAtendentes.getValueAt(pegarSelecao, 0);
                String idd = iddd.toString();
                int id = Integer.parseInt(idd);
                Usuario atd = new Usuario(id);
                DAO dao = new DAO();
                dao.removerAtd(atd);
                JOptionPane.showMessageDialog(null, "Atendete removido com sucesso!");
                readJTableAtd();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldEditarNome1.setText("");
        jTextFieldEditarEmail.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String nome = "%" + jTextFieldProcurar.getText() + "%";

        DAO dao = new DAO();
        ArrayList<Usuario> atendente = new ArrayList<Usuario>();
        try {
            atendente = dao.buscarAtdPorNome(nome);
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel atendentes = (DefaultTableModel) jTableAtendentes.getModel();
        atendentes.setNumRows(0);

        for (Usuario u : atendente) {
            atendentes.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getEmail(),});

        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        jTabbedPane1.setSelectedIndex(2);

        jTextFieldEditarNome1.setText(jTableAtendentes.getValueAt(jTableAtendentes.getSelectedRow(), 1).toString());
        jTextFieldEditarEmail.setText(jTableAtendentes.getValueAt(jTableAtendentes.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void jButtonTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrocarSenhaActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonTrocarSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPasswordFieldEditarSenha.setText("");
        jPasswordFieldEditarConfirmarSenha.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonOkzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkzinhoActionPerformed

        Usuario atd = new Usuario();
        int pegarSelecao = jTableAtendentes.getSelectedRow();
        Object iddd = jTableAtendentes.getValueAt(pegarSelecao, 0);
        String idd = iddd.toString();
        int id = Integer.parseInt(idd);

        if (jTextFieldEditarEmail.getText().equals("") || jTextFieldEditarNome1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios");
        } else {
            atd.setEmail(jTextFieldEditarEmail.getText());
            atd.setNome(jTextFieldEditarNome1.getText());
            atd.setId(id);
            DAO dao = new DAO();

            try {
                dao.atualizarAtd(atd);

                JOptionPane.showMessageDialog(null, "Atendente atualizado com sucesso!");
                readJTableAtd();
                jTextFieldEditarEmail.setText("");
                jTextFieldEditarNome1.setText("");
                jTabbedPane1.setSelectedIndex(1);
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastroAdmin.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Falha técnica, verifique se seu email já não está cadastrado. Caso não esteja, consulte o suporte!", "Falha no Cadastro", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonOkzinhoActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        Usuario atd = new Usuario();
        int pegarSelecao = jTableAtendentes.getSelectedRow();
        Object iddd = jTableAtendentes.getValueAt(pegarSelecao, 0);
        String idd = iddd.toString();
        int id = Integer.parseInt(idd);

        String senha = new String(jPasswordFieldEditarSenha.getPassword());
        String CSenha = new String(jPasswordFieldEditarConfirmarSenha.getPassword());

        if (senha == null || senha.length() == 0 || CSenha == null || CSenha.length() == 0) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
        } else if (senha.equals(CSenha)) {
            atd.setSenha(senha);
            atd.setId(id);
            DAO dao = new DAO();
            try {
                dao.atualizarSenhaAtd(atd);

                JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso!");
                readJTableAtd();
                jPasswordFieldEditarSenha.setText("");
                jPasswordFieldEditarConfirmarSenha.setText("");
                jTabbedPane1.setSelectedIndex(1);
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastroAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Os campos de senha devem ser os mesmos!");
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            try {
                new TelaCadastroAdmin().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastroAtendente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JButton ButtonLimpar;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonOkzinho;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonTrocarSenha;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundo2;
    private javax.swing.JLabel jLabelFundo3;
    private javax.swing.JLabel jLabelFundo4;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldEditarConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldEditarSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAtendentes;
    private javax.swing.JTextField jTextFieldEditarEmail;
    private javax.swing.JTextField jTextFieldEditarNome1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldProcurar;
    // End of variables declaration//GEN-END:variables
}
